name: Build Pull Request
on: [pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
        id: go

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          go test ./... -v -count 5
